# Generated by Django 3.2.13 on 2022-06-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acnequeue',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Initial'), (1, 'Enqueue'), (2, 'Process'), (3, 'Terminate'), (4, 'Resend')], default=0),
        ),
    ]
