# Generated by Django 3.2.13 on 2022-06-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_alter_acnequeue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acnequeue',
            name='time_to_dead',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
