# Generated by Django 3.2.14 on 2022-07-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_alter_acnequeue_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.IntegerField(blank=True, default=0, null=True)),
                ('request_event', models.CharField(blank=True, max_length=50, null=True)),
                ('request_error_message', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
