# Generated by Django 3.2.14 on 2022-08-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='acnequeue',
            name='model',
            field=models.SmallIntegerField(choices=[(0, 'Acne_score'), (1, 'Beauty_score'), (2, 'Age_race'), (3, 'Wrinkles'), (4, 'Skin_disease')], default=0),
        ),
    ]
